### ISSUE TITLE
NEW BUG

### ISSUE THREAD

**Issue by kaysabelle** [radlib/radlib-cordova#21]
# THIS NEEDS TO BE FIXED

When you do "Scan for Readers" then "Get IO Stream," it works the first time but when you connect to another reader it crashes.

**Comment by jeslin** [comment]
Vincent, we were playing around with the assign button and accidentally assigned it to you, but feel free to work on it if you want LOL

**Comment by vinchan** [comment]
Not entirely sure what is trying to happen here, cause "Scan for Readers" needs to be redone. I've said this before but scan does a popup screen in android code, but we're trying to make scan return a json array instead for the html to populate.

**Comment by vinchan** [comment]
Scan (Java popup menu) and Get IO Stream have been removed.
