### ISSUE TITLE
New bug # 2

### ISSUE THREAD

**Issue by jeslin** [radlib/radlib-cordova#22]
# NEW ISSUE AS OF 2/22/15 4:45 PM

~~When you stream two readers, only the one that connected first will be streamed~~ Actually reads from one reader at a time

when you scan and the discovery window is up and you pick something, if the discovery window doesn't go away and you pick something else, the app crashes.

:cry:

**Comment by vinchan** [comment]
I've been aware of this bug since the beginning. It won't be an issue because scan will no longer have the popup screen like that.

**Comment by vinchan** [comment]
The pop up menu no longer occurs so this issue is fixed.

**Comment by kaysabelle** [comment]
Can you elaborate on "pop up menu"? This would be helpful as I work on UI

**Comment by vinchan** [comment]
The pop up menu as in the one built through java. It no longer exists. The one that would say "HC-06 XX:XX:XX:XX:XX:XX" and "Cancel" after a scan.
