### ISSUE TITLE
Database delete entries not working

### ISSUE THREAD

**Issue by vinchan** [radlib/radlib-cordova#38]
I've looked over the code. In theory, a "Delete?" column should appear for the user to check. However, it's impossible to get it to show up for me.

**Comment by kaysabelle** [comment]
Have you pulled the latest? Also, if you have no rows to delete, no "Delete?" column should show up.

**Comment by kaysabelle** [comment]
FIXED with my latest pull request. @jeslin and I both edited the databases.js file at the same time so hers overwrote mine during merge
